log/log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logingApp.urls')),
]

log/logingApp/urls.py
from django.urls import path
from logingApp import views
from django.contrib.auth import views as auth_views

app_name='logingApp'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='logingApp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logingApp/logout.html'), name='logout'),
    path('companys/', views.CompanysListView.as_view(), name='companys'),
]

log/logingApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Company(models.Model):
    name = models.CharField(max_length=50)
    street = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    class Meta:
        ordering = ('id',)
    def __str__(self):
        return self.name

class Factory(models.Model):
    name = models.CharField(max_length=50)
    desctription = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    class Meta:
        ordering = ('company','id')
    def __str__(self):
        return self.name

class Machine(models.Model):
    name = models.CharField(max_length=50)
    desctription = models.TextField()
    type = models.CharField(max_length=50)
    factory = models.ForeignKey(Factory, on_delete=models.CASCADE)
    class Meta:
        ordering = ('factory','id')
    def __str__(self):
        return self.name

class User(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    department = models.CharField(max_length=20)
    phoneNumber = models.CharField(max_length=20)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username

log/logingApp/views.py
from django.shortcuts import get_object_or_404
from logingApp.models import Company, User, Factory, Machine
from logingApp.serializers import CompanySerializer, FactorySerializer
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.
class CompanysListView(LoginRequiredMixin, APIView):
	login_url = ''
	redirect_field_name = ''
	renderer_classes = [TemplateHTMLRenderer]
	template_name = 'logingApp/company_list.html'

	def get(self, request):
		company = User.objects.filter(user = self.request.user).first().company
		factorys =  Factory.objects.filter(company=company)
		cSerializer = CompanySerializer(company)
		fSerializer = FactorySerializer(factorys, many=True)

		context = {}
		context ['companySerializer'] = cSerializer
		context ['factorysSerializer'] = fSerializer

		return Response(context)

log/logingApp/templates/logingApp/company_list.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
{% load logingApp_extras%}
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>Companys</title>
  </head>
  <body>
    <div class="container mt-5" style="marign:auto">
      <a href="{% url 'logingApp:logout' %}" class="float-right btn btn-secondary btn-link" role="button">Logout</a>
      <h4 class="text-info">{{companySerializer.data.name}}</h4>
      <hr>
      <ul class="list-group">
        {%for it in factorysSerializer.data%}
          <li class="list-group-item">
            {{it.name}}
            <ol>
              {%for el in it.id|machines %}
                <li>{{el}}</li>
              {%endfor%}
            </ol>
          </li>
        {%endfor%}
      </ul>
	 </div>
 </body>
</html>

log/logingApp/templates/logingApp/login.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>Log in</title>
  </head>
  <body>
    <div class="container" style="marign:auto">
		<form method="POST">
			{% csrf_token %} <!--form security, django requires-->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Login!</legend>
				{{ form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-outline-info" type="submit">Login</button>
				<!--odkomentiraj pass reset kad ga opet napravis-->
				<small class="text-muted ml-2"><a href="{# url 'password_reset' #}">Zaboravili ste lozinku?</a></small>
			</div>
		</form>
	</div>
  </body>
</html>

log/logingApp/templates/logingApp/logout.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <title>Log in</title>
  </head>
  <body>
    <div class="container">
        <h2>Uspjesno ste izasli iz korisnickog racuna!</h2>
        <div class="border-top pt-3">
          <small class="text-muted">
            <a href="{% url 'logingApp:login' %}">Ulogiraj se</a>
          </small>
        </div>
	</div>
  </body>
</html>